[package]
name    = "hashpay"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
hashpay       = "0x0"
treasury_addr = "0x0"   # replace with actual treasury address at deploy
backend_addr  = "0x0"   # replace with actual backend signer address at deploy
