/// hashpay::escrow  (Sui Move)
///
/// Multi-currency crypto → fiat escrow for HashPay Global.
/// Supports NGN, GHS, KES, XOF, XAF payouts via Afriex / Opay / Flipeet.
///
/// Flow:
///   1. User calls deposit_and_lock<USDC>(coin, order_id, "NGN", amount_out, expiry, sig)
///   2. Backend verifies secp256k1 signature over the quote params
///   3. USDC sent to treasury, EscrowRecord shared object created, DepositEvent emitted
///   4. Backend listens via Sui GraphQL subscription, routes to correct fiat provider
///   5. On success: backend calls mark_paid()  → ReleaseEvent emitted
///   6. On failure: backend calls admin_refund() OR user calls self_refund() after timeout
///
/// Security:
///   - TreasuryCap is held by admin — only admin can mark_paid / admin_refund
///   - Signature verification prevents rate manipulation (MEV protection)
///   - timeout_epoch enforces user self-rescue if backend is unresponsive
///   - EscrowRecord is a shared object — queryable by object ID without event scanning
module hashpay::escrow {
    use sui::coin::{Self, Coin};
    use sui::event;
    use sui::object::{Self, UID};
    use sui::transfer;
    use sui::tx_context::{Self, TxContext};
    use sui::ecdsa_k1;
    use sui::bcs;
    use std::vector;
    use std::string::{Self, String};

    // ── Error codes ──────────────────────────────────────────
    const E_INVALID_SIGNATURE: u64 = 0;
    const E_QUOTE_EXPIRED:     u64 = 1;
    const E_NOT_AUTHORIZED:    u64 = 2;
    const E_WRONG_STATUS:      u64 = 3;
    const E_TIMEOUT_NOT_REACHED: u64 = 4;
    const E_ZERO_AMOUNT:       u64 = 5;
    const E_WRONG_AMOUNT:      u64 = 6;

    // ── Status constants ─────────────────────────────────────
    const STATUS_PENDING:  u8 = 0;
    const STATUS_PAID:     u8 = 1;
    const STATUS_REFUNDED: u8 = 2;

    // ── Capability objects ───────────────────────────────────

    /// Held by the admin/treasury. Required for mark_paid and admin_refund.
    public struct TreasuryCap has key, store {
        id: UID,
    }

    /// Held by the backend signer. Required for mark_paid.
    public struct BackendCap has key, store {
        id: UID,
    }

    // ── Shared escrow record ─────────────────────────────────

    /// Created per deposit. Shared so backend can mutate it by object ID.
    public struct EscrowRecord has key, store {
        id:             UID,
        order_id:       vector<u8>,
        user:           address,
        amount_in:      u64,        // raw on-chain amount (6 decimals for USDC)
        amount_out:     u64,        // locked fiat amount (e.g. 78500 for ₦78,500)
        currency_out:   String,     // "NGN" | "GHS" | "KES" | "XOF" | "XAF"
        coin_type:      String,     // "USDC" | "USDT" | "ETH"
        status:         u8,         // 0=pending, 1=paid, 2=refunded
        timeout_epoch:  u64,        // user can self-refund after this epoch
        provider:       String,     // "afriex" | "opay" | "flipeet" — set by backend
        payout_ref:     String,     // provider's payout reference — set on mark_paid
    }

    // ── Events ───────────────────────────────────────────────

    public struct DepositEvent has copy, drop {
        order_id:     vector<u8>,
        user:         address,
        amount_in:    u64,
        amount_out:   u64,
        currency_out: String,
        coin_type:    String,
        record_id:    address,      // object ID of EscrowRecord for direct lookup
    }

    public struct PaidEvent has copy, drop {
        order_id:   vector<u8>,
        user:       address,
        amount_out: u64,
        currency:   String,
        provider:   String,
        payout_ref: String,
    }

    public struct RefundEvent has copy, drop {
        order_id:  vector<u8>,
        user:      address,
        amount_in: u64,
        reason:    String,
    }

    // ── Module initialiser ───────────────────────────────────

    fun init(ctx: &mut TxContext) {
        // Transfer TreasuryCap and BackendCap to deployer.
        // Deployer must then transfer BackendCap to the backend hot wallet.
        transfer::transfer(TreasuryCap { id: object::new(ctx) }, tx_context::sender(ctx));
        transfer::transfer(BackendCap  { id: object::new(ctx) }, tx_context::sender(ctx));
    }

    // ── deposit_and_lock ─────────────────────────────────────

    /// Entry point called by the user.
    ///
    /// Parameters:
    ///   coin         — the USDC/USDT/ETH coin to lock
    ///   order_id     — unique order ID generated by the frontend (UUID bytes)
    ///   currency_out — target fiat currency: b"NGN", b"GHS", b"KES", b"XOF", b"XAF"
    ///   coin_type    — human-readable coin name: b"USDC"
    ///   amount_out   — locked fiat amount in smallest unit (e.g. 78500 = ₦78,500)
    ///   expiry       — epoch after which the quote is invalid
    ///   signature    — secp256k1 signature by backend over the quote message
    ///   backend_pubkey — backend's secp256k1 public key (33 bytes compressed)
    ///   timeout_epochs — how many epochs until user can self-refund (e.g. 100 ≈ 8h)
    public entry fun deposit_and_lock<T>(
        coin:           Coin<T>,
        order_id:       vector<u8>,
        currency_out:   vector<u8>,
        coin_type_name: vector<u8>,
        amount_out:     u64,
        expiry:         u64,
        signature:      vector<u8>,
        backend_pubkey: vector<u8>,
        timeout_epochs: u64,
        ctx:            &mut TxContext,
    ) {
        let amount_in = coin::value(&coin);
        assert!(amount_in > 0, E_ZERO_AMOUNT);

        let epoch  = tx_context::epoch(ctx);
        let sender = tx_context::sender(ctx);

        // ── 1. Quote expiry check ────────────────────────────
        assert!(epoch < expiry, E_QUOTE_EXPIRED);

        // ── 2. Signature verification ────────────────────────
        // Message = order_id || amount_in (BCS) || amount_out (BCS) || expiry (BCS)
        let msg = build_quote_message(&order_id, amount_in, amount_out, expiry);
        assert!(
            verify_backend_sig(&msg, &signature, &backend_pubkey),
            E_INVALID_SIGNATURE
        );

        // ── 3. Send coin to treasury ─────────────────────────
        transfer::public_transfer(coin, @treasury_addr);

        // ── 4. Create shared EscrowRecord ────────────────────
        let record = EscrowRecord {
            id:            object::new(ctx),
            order_id,
            user:          sender,
            amount_in,
            amount_out,
            currency_out:  string::utf8(currency_out),
            coin_type:     string::utf8(coin_type_name),
            status:        STATUS_PENDING,
            timeout_epoch: epoch + timeout_epochs,
            provider:      string::utf8(b""),
            payout_ref:    string::utf8(b""),
        };

        let record_id = object::uid_to_address(&record.id);

        // ── 5. Emit event ────────────────────────────────────
        event::emit(DepositEvent {
            order_id,
            user:         sender,
            amount_in,
            amount_out,
            currency_out: string::utf8(currency_out),
            coin_type:    string::utf8(coin_type_name),
            record_id,
        });

        // ── 6. Share record so backend can mutate it ─────────
        transfer::share_object(record);
    }

    // ── mark_paid ────────────────────────────────────────────

    /// Called by backend after fiat provider confirms payout.
    /// Requires BackendCap — only the backend hot wallet can call this.
    public entry fun mark_paid(
        _cap:       &BackendCap,
        record:     &mut EscrowRecord,
        provider:   vector<u8>,
        payout_ref: vector<u8>,
        _ctx:       &mut TxContext,
    ) {
        assert!(record.status == STATUS_PENDING, E_WRONG_STATUS);

        record.status     = STATUS_PAID;
        record.provider   = string::utf8(provider);
        record.payout_ref = string::utf8(payout_ref);

        event::emit(PaidEvent {
            order_id:   record.order_id,
            user:       record.user,
            amount_out: record.amount_out,
            currency:   record.currency_out,
            provider:   record.provider,
            payout_ref: record.payout_ref,
        });
    }

    // ── admin_refund ─────────────────────────────────────────

    /// Called by backend when payout fails after all retries.
    /// Requires TreasuryCap. Backend must send the coin back from treasury.
    public entry fun admin_refund<T>(
        _cap:   &TreasuryCap,
        record: &mut EscrowRecord,
        coin:   Coin<T>,
        reason: vector<u8>,
        _ctx:   &mut TxContext,
    ) {
        assert!(record.status == STATUS_PENDING, E_WRONG_STATUS);
        assert!(coin::value(&coin) == record.amount_in, E_WRONG_AMOUNT);

        record.status = STATUS_REFUNDED;

        transfer::public_transfer(coin, record.user);

        event::emit(RefundEvent {
            order_id:  record.order_id,
            user:      record.user,
            amount_in: record.amount_in,
            reason:    string::utf8(reason),
        });
    }

    // ── self_refund ──────────────────────────────────────────

    /// Called by the user themselves after timeout_epoch has passed
    /// and the backend has not confirmed payment.
    /// Backend must have sent the coin back to treasury first.
    public entry fun self_refund<T>(
        record: &mut EscrowRecord,
        coin:   Coin<T>,
        ctx:    &mut TxContext,
    ) {
        let sender = tx_context::sender(ctx);
        let epoch  = tx_context::epoch(ctx);

        assert!(record.user == sender,              E_NOT_AUTHORIZED);
        assert!(record.status == STATUS_PENDING,    E_WRONG_STATUS);
        assert!(epoch > record.timeout_epoch,       E_TIMEOUT_NOT_REACHED);
        assert!(coin::value(&coin) == record.amount_in, E_WRONG_AMOUNT);

        record.status = STATUS_REFUNDED;

        transfer::public_transfer(coin, sender);

        event::emit(RefundEvent {
            order_id:  record.order_id,
            user:      sender,
            amount_in: record.amount_in,
            reason:    string::utf8(b"USER_SELF_REFUND_AFTER_TIMEOUT"),
        });
    }

    // ── View helpers ─────────────────────────────────────────

    public fun get_status(record: &EscrowRecord): u8 { record.status }
    public fun get_user(record: &EscrowRecord): address { record.user }
    public fun get_amount_in(record: &EscrowRecord): u64 { record.amount_in }
    public fun get_amount_out(record: &EscrowRecord): u64 { record.amount_out }
    public fun get_currency_out(record: &EscrowRecord): String { record.currency_out }
    public fun get_timeout_epoch(record: &EscrowRecord): u64 { record.timeout_epoch }
    public fun is_pending(record: &EscrowRecord): bool { record.status == STATUS_PENDING }
    public fun is_paid(record: &EscrowRecord): bool { record.status == STATUS_PAID }

    // ── Internal helpers ─────────────────────────────────────

    /// Build the canonical message the backend signs.
    /// msg = order_id || BCS(amount_in) || BCS(amount_out) || BCS(expiry)
    fun build_quote_message(
        order_id:   &vector<u8>,
        amount_in:  u64,
        amount_out: u64,
        expiry:     u64,
    ): vector<u8> {
        let msg = vector::empty<u8>();
        vector::append(&mut msg, *order_id);
        vector::append(&mut msg, bcs::to_bytes(&amount_in));
        vector::append(&mut msg, bcs::to_bytes(&amount_out));
        vector::append(&mut msg, bcs::to_bytes(&expiry));
        msg
    }

    /// Verify secp256k1 signature.
    /// Uses keccak256 hashing (hash_function = 0).
    fun verify_backend_sig(
        msg: &vector<u8>,
        sig: &vector<u8>,
        pk:  &vector<u8>,
    ): bool {
        // ecdsa_k1::secp256k1_verify(sig, pk, msg, hash_function)
        // hash_function: 0 = keccak256, 1 = sha256
        ecdsa_k1::secp256k1_verify(sig, pk, msg, 0)
    }
}
